name: flutter_test_espresso
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  provider: ^6.1.2

dev_dependencies:
  espresso: ^0.3.0+7
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  uses-material-design: true
